spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/document-management
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true # se o banco jรก tiver dados

  logging:
    level:
      org.flywaydb: DEBUG

